apiVersion: v1
kind: Service
metadata:
  name: flask-app-ecs-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort

